# See dztech_dz60rgb_wkl/keymaps/haunt98/config.h

VIA_ENABLE = no

LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

BOOTMAGIC_ENABLE = yes

DEBOUNCE_TYPE = sym_eager_pk
